apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital
      app.kubernetes.io/name: xjelinekj-ambulance-wl
      wac-fiit.github.io/project: xjelinekj-ambulance-wl
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../../apps/xjelinekj-ambulance-ufe
  - ../../../apps/xjelinekj-ambulance-webapi

components:
  - ../../../components/version-release

patches:
  - target:
      group: polyfea.github.io
      version: v1alpha1
      kind: WebComponent
      name: xjelinekj-ambulance-ufe-content
    patch: |-
      - op: replace
        path: /spec/attributes/1/value
        value: /xjelinekj-api
